version: '3.5'
services:
  comunidade-debug:
    build: .
    volumes: 
      - .:/var/www/gateway
      - /var/www/gateway/node_modules
    restart: always
    hostname: comunidade
    command: npm run start:debug
    ports: 
      - 9228:9228
    env_file:
      - .env
    networks:
      - backend
  comunidade-dev:
    build: .
    volumes: 
      - .:/var/www/gateway
      - /var/www/gateway/node_modules
    restart: always
    hostname: comunidade
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external:
      name: cartografia-network